dist: trusty
sudo: false
language: node_js
node_js:
- 6.11.1
notifications:
  email:
    on_failure: change
    on_success: change
branches:
  only:
  - master
  - stage
  - prod
cache:
  bundler: true
  directories:
  - node_modules
deploy:
  provider: firebase
  token:
    secure: o0GTMz8eQ+y0D4e2uMZ2cy/X9SgOv+dL5d3/eoht6r22DUD60K7sHn0+TcCa1ro5XPsVO8p8Hxm793LRaK+e9HhyXMAQajKZGQ/NZW2A28PTJoltgpxLVsM/bJ43Kt1/7j6R/tR3+saPzkMXF9ZBgofv8N+c+OXxMLKMMzrFxx3/69QSytyMaX6g1rwMtnlQwSZ87Stggbzs0HhNApxnLI26w6NMWsGjAupN8G7RsEvJCrk/mEvFlIzpMWzA+9hwFXwhbCWRgzYY9uF9vibEuQcaCFbVuMNrc+fa4S+tuRB7bx2al1qOHKmZmJO/l6/ahOTRIgsI4g0Imne+UjxCG0PFE+MnfBSrD09o8qg8YjUfbg7ylmUsWufkCEOdJzVFVrJEo8BqsaadTTx9Yg+ueeeuHKeWyztHtaEzCfKDlOQZHVhd2H+CDyTwi88k6DOXNVdHy/fHU6JdOHR4TmxP9EouJqmPtJJ39e1g3+OKTggtYW/dHP9GQwpfx5K7Ac5h1x//rmzhTahduEK+qsoQ8RHkW+qw/Zqj50czYv7jKSfR7BjVBluY61Vn3hCjZxSm4anJyZYgOYS0v4rfw8pW/OwKFw6eD6he48dUKrGSwsQdqqBejz3rKiyUnRsZnzLXC9hP2nf2Axali1ej2tyo786sQdXAEu/fAifl/ouS75Y=
  project: media-d7281
install:
- npm set progress=false
- npm i
- npm i -g firebase-ci
script:
- firebase-ci createConfig
- npm run test
- npm run build
addons:
  code_climate:
    repo_token: "$CODE_CLIMATE"
after_success:
- firebase-ci deploy -s
env:
  global:
  - firebase_token: 1/SgjpthnR5QmuFNzesYt1beVcsu-AV79Az8lz4YdPMj0
  - secure: o0GTMz8eQ+y0D4e2uMZ2cy/X9SgOv+dL5d3/eoht6r22DUD60K7sHn0+TcCa1ro5XPsVO8p8Hxm793LRaK+e9HhyXMAQajKZGQ/NZW2A28PTJoltgpxLVsM/bJ43Kt1/7j6R/tR3+saPzkMXF9ZBgofv8N+c+OXxMLKMMzrFxx3/69QSytyMaX6g1rwMtnlQwSZ87Stggbzs0HhNApxnLI26w6NMWsGjAupN8G7RsEvJCrk/mEvFlIzpMWzA+9hwFXwhbCWRgzYY9uF9vibEuQcaCFbVuMNrc+fa4S+tuRB7bx2al1qOHKmZmJO/l6/ahOTRIgsI4g0Imne+UjxCG0PFE+MnfBSrD09o8qg8YjUfbg7ylmUsWufkCEOdJzVFVrJEo8BqsaadTTx9Yg+ueeeuHKeWyztHtaEzCfKDlOQZHVhd2H+CDyTwi88k6DOXNVdHy/fHU6JdOHR4TmxP9EouJqmPtJJ39e1g3+OKTggtYW/dHP9GQwpfx5K7Ac5h1x//rmzhTahduEK+qsoQ8RHkW+qw/Zqj50czYv7jKSfR7BjVBluY61Vn3hCjZxSm4anJyZYgOYS0v4rfw8pW/OwKFw6eD6he48dUKrGSwsQdqqBejz3rKiyUnRsZnzLXC9hP2nf2Axali1ej2tyo786sQdXAEu/fAifl/ouS75Y=
  - FIREBASE_TOKEN: 1/SgjpthnR5QmuFNzesYt1beVcsu-AV79Az8lz4YdPMj0