dist: trusty
sudo: false
language: node_js
node_js:
- 6.11.1
notifications:
  email:
    on_failure: change
    on_success: change
branches:
  only:
  - master
  - stage
  - prod
cache:
  bundler: true
  directories:
  - node_modules
deploy:
  provider: firebase
  project: media-d7281
install:
- npm set progress=false
- npm i
- npm i -g firebase-ci
script:
- firebase-ci createConfig
- npm run test
- npm run build
addons:
  code_climate:
    repo_token: "$CODE_CLIMATE"
after_success:
- firebase-ci deploy -s
env:
  global:
  - FIREBASE_TOKEN: 1/uJ8YmSwKLfYKD_v3Yspr1nnjd4zxDnbLZAHLwnbZz9A